[package]
name = "waiir"
version = "0.1.0"
authors = ["阿飞 <jinlongfei@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
